### ISSUE TITLE
Dim lights doens't work directly

### ISSUE THREAD

**Issue by joeyvanderbeek** [swttt/HomeyDash#1]
**What OS and browser are you using?** 
Android 7.0 - standard internet browser

**What did you try to achieve?**
Dim the lights

**What was the result?**
Clicked the light, slider dissapeared directly. 
When i click the button and 'slide' directly after clicking it, the slider will stay.

**What did you expect as result?**
Directly the slider.

**Comment by swttt** [comment]
Workaround is possible like how its implemented now. But the modal triggers on a pressup event, and thats not the way how it should behave... will workout a solution tho.

**Comment by swttt** [comment]
Should be fixed now, but might need to decrease the long press time :)
