### ISSUE TITLE
Zones not visible in landscape modus Ipad

### ISSUE THREAD

**Issue by Rocodamelshe** [swttt/HomeyDash#21]
**What OS and browser are you using?**

IOS 9.2.1. Safari and Chrome browser

**What did you try to achieve?**

Tried to select a zone in landscape modus

**What was the result?**

Zones disappear within 2 seconds when in landscape modus

**What did you expect as result?**

Zones stay visible, even in landscape modus

**Any other remarks**

Are there also Homeyda.sh T-shirts?

**Comment by swttt** [comment]
Could you test this on https://beta.homeyda.sh if it still happens?

**Comment by Rocodamelshe** [comment]
Zones are back! Good work!
