### ISSUE TITLE
0 is displayed as dash ( - )

### ISSUE THREAD

**Issue by caseda** [swttt/HomeyDash#3]
**What OS and browser are you using?**
This ons will be for all devices

**What did you try to achieve?**
View the lux outside which is 0 currently, but it is displayed as a - meaning "null"

**What was the result?**

...

**What did you expect as result?**
Check if there is really a value `typeof value != 'undefined'`, and not `!value`

**Any other remarks**
I hate this tablet for text input...

**Comment by swttt** [comment]
Should be fixed 😀
Can you confirm? Since all my sensors went crazy and are displaying null 😁

**Comment by caseda** [comment]
Yup, it's fixed 😄 awesome
