### ISSUE TITLE
[switchlishd] Can't switch device

### ISSUE THREAD

**Issue by 3vad** [swttt/HomeyDash#49]
**What OS and browser are you using?*
 iOS safari /chrome

**What did you try to achieve?**
in the next version switchlisthd, switches not updating/ switching 
...
from quasar v0.15.6 docs
In previous versions you would listen for @change event to detect changes. Now you can listen to @input for immediate changes or @change for lazy update. etc

...

**Comment by swttt** [comment]
Should be fixed in the beta, if not please re-open.
