### ISSUE TITLE
Sidescrolling zones does not work

### ISSUE THREAD

**Issue by antigreja** [swttt/HomeyDash#5]
**What OS and browser are you using?**

Chrome and Safari on iOs

**What did you try to achieve?**

In the sidebar under devices scroll down to zones not visible in the list. 

**What was the result?**

Scrolling is not possible, it selects the zone where you start scrolling with your finger when you leave the spot. 

**What did you expect as result?**

That it would scroll down the list. 

**Any other remarks**

**Comment by swttt** [comment]
Fixed
