### ISSUE TITLE
Notifications for motion sensor are displayed behind the name of the sensos

### ISSUE THREAD

**Issue by antigreja** [swttt/HomeyDash#6]
**What OS and browser are you using?**

iOs Safari & Chrome on an iPhone and iPad

**What did you try to achieve?**

Check the motion sensor

**What was the result?**

When motion is detected the green notification 'MOTION DETECTED' is pleced behind the name of the sensor.

**What did you expect as result?**

no overlays

**Any other  remarks**
![img_2479 edited](https://user-images.githubusercontent.com/18414525/32144500-083e2ed0-bcba-11e7-934d-3c8323f93f55.PNG)

...

**Comment by swttt** [comment]
Should be fixed in the current build, if not please re-open this issue.
