### ISSUE TITLE
[enhancement] Switch List - Find the right "thing"

### ISSUE THREAD

**Issue by BPC83** [swttt/HomeyDash#75]
in my case, when I create a switch list, and have to select things for the switch list, in the drop down, things are only named by "thing" that means that I have 5 items called "ceiling light" it is a bit hard to fint the right "thing" have to try them all, ore guess what is what, could be nice, if it was also named by location..

When the switch list is created, the "thing" is named with location under.. thats fine...

**Comment by swttt** [comment]
Oh valid point, let see if i can squeeze this in tonight.

**Comment by swttt** [comment]
Added for other widgets as well in current beta and stable release.
