### ISSUE TITLE
Dim device function "lags" 

### ISSUE THREAD

**Issue by ghost** [swttt/HomeyDash#78]
**What OS and browser are you using?**

Android Chrome & Fully Browser

**What version are you using?**

Beta and stable, tried both

**What did you try to achieve?**

When I add a Dim device function on the dashboard and e.g. Swipe from 10% to 100%
The lamp fluctuates in brightness.
So does the button on the dim slider: e.g. The button on the slider fluctuates from 20% to 100 to 43 to 86 to 60 to up to 100.
I can't explain it better than this. 

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by ghost** [comment]
What did you expect as result?

That the brightness would adjust accordingly and promptly. 
Without these weird spikes

**Comment by jghaanstra** [comment]
This PR should fix it.

https://github.com/swttt/HomeyDash/pull/79

**Comment by ghost** [comment]
Thank you!

**Comment by swttt** [comment]
Merged into the beta, closing this now.
