### ISSUE TITLE
Overalle energy consumption overview

### ISSUE THREAD

**Issue by BPC83** [swttt/HomeyDash#8]
It is really not an issue, but you asked me to create an issue, I´am new to GitHub, so maybe I´am placing it the wrong place, so foregive me..

Copy from Athom forum:
I would really like to see, possibly on a separate page, an overview of total power consumption, possibly with consumption yesterday and today, last week, last month, last year and so on ..
if it is possible

----

The thing I want, is to be able to see my overalle kwh used today, and also listed yesterday, last week, ant this week until today, so it is possible to see if the power consumption rises, and find out why..

Also, I would be nice, if it was maked in a dynamic way, so maybe a page, where I could choose what meters to be shown, so for instance, I could make a overview over the kids room, and make I a challenge fore them to save energy, (guess who is paying fore the energy)

**Comment by swttt** [comment]
This is something that i do would like to implement in a separate view some day, but isn't part of any roadmap soon. There will be an option to use a widget for that kind of information on the dashboard view (once its done)

**Comment by swttt** [comment]
I actually played around with your idea and implemented a part of it already.
Hope this actually is what you meant.

Still to do is some minor tweaking and adding a graph below for the last 30 days.

**Comment by swttt** [comment]
Closing this issue while i think its implemented like you wanted.
If not, please re-open.
