### ISSUE TITLE
Device duplicates (Blink Camera)

### ISSUE THREAD

**Issue by jasperbollen** [swttt/HomeyDash#9]
Bink camera's are showing up twice at HomeyDash. This is probably due to the capabilities. 
Once, the device shows with the on/off capability (on click showing on/off & Temp capability).
The second time the device shows with the temp capability (on click showing all capabilities).

The device has the following capabilities:
- onoff
- measure_temperature
- custom_capability_1 (wifi_signal)
- custom_capability_2 (battery_state)
- custom_capability_3 (clip_length)
- custom_capability_4 (last_vid)

Hope the image provides enough information (Woonkamer = the blink device)
![dash](https://user-images.githubusercontent.com/28871579/34033369-42ca00b2-e17a-11e7-91a2-a0a5cc156641.png)

**Comment by swttt** [comment]
Could you clear your cache and see if it just shows the 2nd device now?

**Comment by swttt** [comment]
Fixed in the current release
